import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  UserOutline,
  LoginOutline,
  LogoutOutline,
  SettingOutline,
  FolderOutline,
  HomeOutline,
  PlusOutline,
  DownOutline,
  UpOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  UserOutline,
  LoginOutline,
  LogoutOutline,
  SettingOutline,
  FolderOutline,
  HomeOutline,
  PlusOutline,
  DownOutline,
  UpOutline,
];
